on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dart:stable
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 👷 Install Dependencies
        timeout-minutes: 1
        run: |
          flutter pub get
      - name: Run tests
        run: flutter test --concurrency=6 --platform vm --coverage=coverage test/
        timeout-minutes: 2

      - name: 🧪 Run tests
        timeout-minutes: 2
        run: |
          flutter test -r github -j 6 --coverage test/control_test.dart

      - name: 📥 Upload coverage to Codecov
        timeout-minutes: 1
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info